// =============================================================================
// FILE: src/components/legal/prose.tsx
// PURPOSE: Small typographic primitives shared by the policy pages.
//
// WHY THESE EXIST: the policy pages are long-form prose, which is the one thing
//          a utility-first stylesheet is awkward at — repeating the same six
//          Tailwind classes on ninety paragraphs guarantees they drift apart.
//          @tailwindcss/typography would solve it, but it is not a dependency of
//          this project and adding one for five static pages is not worth it, so
//          these thin wrappers carry the styles instead.
//
// All are Server Components: policy text is static and needs no interactivity.
// =============================================================================

import type { ReactNode } from "react";

// -----------------------------------------------------------------------------
// A numbered top-level clause. Policies are referenced in conversation and in
// correspondence ("as set out in section 7"), so the numbering is content rather
// than decoration and is passed in explicitly rather than generated by CSS
// counters — CSS numbering does not survive copy-paste into an email.
//
// `id` gives every clause a stable deep link (e.g. /privacy#your-rights).
// -----------------------------------------------------------------------------
export function Clause({
  id,
  number,
  title,
  children,
}: {
  id: string;
  number: number;
  title: string;
  children: ReactNode;
}) {
  return (
    <section id={id} className="scroll-mt-28">
      <h2 className="text-xl sm:text-2xl font-semibold text-white mb-4">
        <span className="text-cyan-400 tabular-nums">{number}.</span> {title}
      </h2>
      <div className="space-y-4">{children}</div>
    </section>
  );
}

// A sub-heading within a clause, for policies that need a second level.
export function SubHeading({ children }: { children: ReactNode }) {
  return (
    <h3 className="text-base sm:text-lg font-semibold text-slate-100 mt-6 mb-2">
      {children}
    </h3>
  );
}

export function P({ children }: { children: ReactNode }) {
  return <p className="text-slate-300 leading-relaxed">{children}</p>;
}

export function UL({ children }: { children: ReactNode }) {
  return (
    <ul className="space-y-2 pl-1">
      {children}
    </ul>
  );
}

// Uses a styled span rather than a list-style marker so the bullet picks up the
// brand accent while the text stays aligned across wrapped lines.
export function LI({ children }: { children: ReactNode }) {
  return (
    <li className="flex gap-3 text-slate-300 leading-relaxed">
      <span aria-hidden="true" className="text-cyan-400 select-none flex-shrink-0">
        &bull;
      </span>
      <span className="min-w-0">{children}</span>
    </li>
  );
}

// Emphasised inline term — used for defined terms on first use.
export function Term({ children }: { children: ReactNode }) {
  return <strong className="font-semibold text-slate-100">{children}</strong>;
}

// An external or internal link styled consistently across all policies.
export function A({ href, children }: { href: string; children: ReactNode }) {
  const isExternal = href.startsWith("http");

  return (
    <a
      href={href}
      // noreferrer alongside noopener: these links point at our subprocessors'
      // policies, and there is no reason to leak our page URL to them.
      {...(isExternal ? { target: "_blank", rel: "noopener noreferrer" } : {})}
      className="text-cyan-400 underline underline-offset-2 hover:text-cyan-300 transition-colors break-words"
    >
      {children}
    </a>
  );
}

// -----------------------------------------------------------------------------
// A called-out box for material the reader must not skim past — the AI accuracy
// disclaimer, the "no warranty" summary, the limitation of liability.
// -----------------------------------------------------------------------------
export function Callout({ children }: { children: ReactNode }) {
  return (
    <div className="rounded-xl border border-cyan-500/25 bg-cyan-500/5 px-5 py-4">
      <div className="space-y-3 text-slate-200 text-sm leading-relaxed">{children}</div>
    </div>
  );
}

// -----------------------------------------------------------------------------
// Definition-style rows, used where a policy has to enumerate categories against
// explanations (data collected vs. purpose, subprocessor vs. role).
//
// A real <table> would be more semantically precise, but tables of two columns
// with paragraph-length cells are what break policy pages on phones. A
// description list carries the same semantics and reflows cleanly.
// -----------------------------------------------------------------------------
export function DefinitionList({ children }: { children: ReactNode }) {
  return <dl className="space-y-4">{children}</dl>;
}

export function Definition({ term, children }: { term: string; children: ReactNode }) {
  return (
    <div className="rounded-xl border border-white/10 bg-white/[0.03] px-5 py-4">
      <dt className="font-semibold text-slate-100 mb-1">{term}</dt>
      <dd className="text-slate-300 text-sm leading-relaxed">{children}</dd>
    </div>
  );
}
